plugins {
    id "com.android.application"
}

def versionMajor = (project.findProperty("versionName") ?: "1.0.0")
def versionInt = (project.findProperty("versionCode") ?: "1").toInteger()

android {
    namespace "com.leastudio.app"
    compileSdk 34
    defaultConfig {
        applicationId "com.leastudio.app"
        minSdk 24
        targetSdk 34
        versionCode versionInt
        versionName versionMajor
    }
    signingConfigs {
        release {
            storeFile file("lea-release.keystore")
            storePassword "leastudio"
            keyAlias "lea"
            keyPassword "leastudio"
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            signingConfig signingConfigs.release
        }
        debug {
            signingConfig signingConfigs.release
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    implementation "androidx.appcompat:appcompat:1.7.0"
    implementation "androidx.webkit:webkit:1.11.0"
}
